上傳凝視與中盤概論
puyotw/core-site pull request #12
Opened 2019-01-04 09:32 UTC by aclivtak

2019-01-04 09:56 UTC, kar8uncle requested changes
要寫個`_wiki/C_tactics/e_observation/index.md`，主要用來給`e_observation`這一層的摺疊起個中文名字，可以參考其他資料夾裡面的`index.md`。不過沒有了他也能用我有點意外XD

內容我就沒看啦，a神寫的內容怎麼敢說錯XD

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
>  ### 概論
`### 概論`不用特別寫了，每一頁的title會自動寫出來。

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
>  ## 同消的得分
不要用`#`、`##`控制標題大小喔。是第一層就用`#`，第二層就用`##`。如果覺得第一層標題大小太大，我們可以改style。

所以這些`##`都要改成`#`吧，還有其他file也是。

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
> +落下得分的計算方式簡單，按住下的時候經過場上的一格就是加一分。連鎖得分的計算比較複雜，牽涉了連鎖數、同消的個數，以及同消的顏色數。其中對中盤戰重要的一點是，**在消掉的氣泡數一樣的前提下，追求高同消與追求高連鎖的分數可能差不多，甚至更多！**例如，同樣是消掉十顆氣泡，[這個情況](http://1st.geocities.jp/mattulwan/puyo_simulator/?a55c2a4b
這些連結把md弄得有點長呢。你可以寫成：
```
內容內容[連結][simlink1]，內容內容⋯⋯

[simlink1]: http://....
```

就是把`[simlink1]`的實質網址放在段落之後就可以了。

在[README.md](https://raw.githubusercontent.com/puyotw/core-site/master/README.md)裡，`[md-guide]`也是用一樣的做法，可以參考看看。

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +*	對手的關鍵氣泡是否都放上了？
這裡的空白有點奇怪？怎麼這麼多XD

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +而在另些情況，可能真的得盯著對手看，必要的話放慢自己的速度，例如
nit: 這行上面加個空行。

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +※給初～中級者的話：以上舉的例子可能有些難，但目的只是要對凝視的使用方法給出較具體的描述；理解到凝視不一定需要一直盯著對手，能藉著利用周邊視野或瞄對手場地來獲得資訊即可。
可能用blockquote更醒目？

> 給初～中級者的話：以上舉的例子可能有些難，但目的只是要對凝視的使用方法給出較具體的描述；理解到凝視不一定需要一直盯著對手，能藉著利用周邊視野或瞄對手場地來獲得資訊即可。

2019-01-04 09:56 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +//以上可能須搭配simulator舉例
這個是comment麼？是的話寫成

```
{%- comment -%}
以上可能須搭配simulator舉例
{%- endcomment -%}
```

2019-01-04 10:18 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
>  ## 同消的得分
剛看了一下，title自動變成h1，`#`也是h1呢。 🤔

@crs38c28 你怎麼看？是不是都應該由`##`開始？

2019-01-04 10:32 UTC, crs38c28 commented on _wiki/C_tactics/b_middle/i_intro.md
>  ## 同消的得分
從 ```##``` 開始應該好一些 不然跟title一樣大有點怪XD

2019-01-04 10:34 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
>  ## 同消的得分
那這邊就不要改了～

2019-01-04 10:37 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +##練習凝視 [^2]
nit: `##`後加個空白

2019-01-04 10:45 UTC, crs38c28 commented on _wiki/C_tactics/b_middle/i_intro.md
> +落下得分的計算方式簡單，按住下的時候經過場上的一格就是加一分。連鎖得分的計算比較複雜，牽涉了連鎖數、同消的個數，以及同消的顏色數。其中對中盤戰重要的一點是，**在消掉的氣泡數一樣的前提下，追求高同消與追求高連鎖的分數可能差不多，甚至更多！**例如，同樣是消掉十顆氣泡，[這個情況](http://1st.geocities.jp/mattulwan/puyo_simulator/?a55c2a4b
我認為可以用Table+圖片來做呢
點選編輯器的圖像生成 然後把圖片傳到imgur上
像是
(此為kramdown語法 與Markdown不同)
```
|-----------------+------------|
| 兩連鎖600分      |一連鎖700分  |
|:---------------:|:----------:|
| ![兩連鎖600分](https://i.imgur.com/IAGhqMu.png) |![一連鎖700分](https://i.imgur.com/MKf9XNQ.png) |
|-----------------+------------|
```
結果:
![Table](https://i.imgur.com/X4uSdSP.png)

2019-01-04 16:43 UTC, aclivtak commented on _wiki/C_tactics/e_observation/observation.md
> +※給初～中級者的話：以上舉的例子可能有些難，但目的只是要對凝視的使用方法給出較具體的描述；理解到凝視不一定需要一直盯著對手，能藉著利用周邊視野或瞄對手場地來獲得資訊即可。
有道理

2019-01-04 16:43 UTC, aclivtak commented on _wiki/C_tactics/e_observation/observation.md
> +//以上可能須搭配simulator舉例
是comment，想說有simulator之後加東西，加完後刪掉這句 XD

2019-01-04 17:00 UTC, aclivtak commented on _wiki/C_tactics/e_observation/observation.md
> +*	對手的關鍵氣泡是否都放上了？
可能不小心弄到全形輸入 XD

2019-01-04 17:05 UTC, aclivtak commented on _wiki/C_tactics/b_middle/i_intro.md
> +落下得分的計算方式簡單，按住下的時候經過場上的一格就是加一分。連鎖得分的計算比較複雜，牽涉了連鎖數、同消的個數，以及同消的顏色數。其中對中盤戰重要的一點是，**在消掉的氣泡數一樣的前提下，追求高同消與追求高連鎖的分數可能差不多，甚至更多！**例如，同樣是消掉十顆氣泡，[這個情況](http://1st.geocities.jp/mattulwan/puyo_simulator/?a55c2a4b
原來如此

2019-01-04 19:21 UTC, kar8uncle reviewed
大致可以了，謝謝～

話說應該要給二ダブル起個中文名？畢竟要來看這些中文百科的一定有不會日文的人呢。

2019-01-04 19:21 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
> +另舉一例，同樣消掉十二顆氣泡，[這個情況]是三連鎖1000分，而[這個情況]是兩連鎖920分，只少了一～兩顆障礙氣泡，同樣給對手更短的反應時間。
應該是 `[這個情況][simlink1]`，下面是`[simlink1]: http://...`，不然全部都叫`[這個情況]`，他也不知道要放哪一條xD

2019-01-04 19:21 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +*	對手的關鍵氣泡是否都放上了？
空白好像沒修？還是是故意留空白的？

2019-01-04 19:21 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/index.md
> +title:  凝視的技巧
這個跟observation.md一樣的標題誒。我沒回去看大綱，但這個分類之下還有別的文章麼？只有一篇的話，不用特意開一個分類了。把observation.md移到C_tactics之下就可以了。

2019-01-04 19:21 UTC, kar8uncle commented on _wiki/C_tactics/e_observation/observation.md
> +理解到凝視不一定需要一直盯著對手，能藉著利用周邊視野或瞄對手場地來獲得資訊即可。
很可惜中文在markdown分行處也會被加個半形空白，所以我們不要開新行吧。

2019-01-05 15:59 UTC, aclivtak commented on _wiki/C_tactics/b_middle/i_intro.md
> +另舉一例，同樣消掉十二顆氣泡，[這個情況]是三連鎖1000分，而[這個情況]是兩連鎖920分，只少了一～兩顆障礙氣泡，同樣給對手更短的反應時間。
!?可是他放的是對的連結 XDDD

2019-01-05 16:17 UTC, aclivtak commented on _wiki/C_tactics/e_observation/index.md
> +title:  凝視的技巧
好，那我就叫e_observation.md吧

2019-01-05 22:40 UTC, kar8uncle commented on _wiki/C_tactics/b_middle/i_intro.md
> +另舉一例，同樣消掉十二顆氣泡，[這個情況]是三連鎖1000分，而[這個情況]是兩連鎖920分，只少了一～兩顆障礙氣泡，同樣給對手更短的反應時間。
可能github會對？ 🤔

反正對錯很難說～保險一點好

2019-01-06 01:46 UTC, kar8uncle approved these changes

2019-01-06 01:47 UTC, merged