上傳障礙氣泡量公式
puyotw/core-site pull request #14
Opened 2019-01-10 15:30 UTC by aclivtak

2019-01-11 02:18 UTC, kar8uncle requested changes

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +| 19 |  512  |
要不要總結為

當 k = 1, R(k) = 0  
當 2 <= k <= 5, R(k) = 2^(k + 1)  
當 k >= 6, R(k) = (k - 3) * 32

這樣，兩顆消這些可以超過19連的模式也包括到了。但是，可能也要求證一下這個總結是對的。

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +也就是（$\sum_{k=1}^{n}$第$k$連鎖得分＋連鎖發動前累積的落下得分）除以$70$的商；這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
這裡不用\text?

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +\text{送給對手的障礙氣泡總數} = \left\lfloor\frac{\sum\text{第$k$連鎖得分}S_k + \text{連鎖發動前累積的落下得分}}{70}\right\rfloor
可以把summation寫這裡？那下面不用再寫。把1/70寫在括號外面，那summation就可以維持displaystyle了。

還有突然想起margin time時不是70 Kappa，所以也是個變數。

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +* 第$k$連鎖的連結數$l$
這個連結數要寫明是「每個連結的氣泡數」？不然以為只有一個數字。

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +10t\left( R(k)+C(c)+\sum_{i=1}^{g} L(l_i) \right), \ 若(k,t)\neq(1,4)
中文要`\text`

還有不知道MathJax給不給用cases environment🤔

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +title: 障礙氣泡量公式
我覺得可以開始想這些頁面該有甚麼標籤了。

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +### 1. 氣泡數$t$
@crs38c28 看來要讓`h3`自動顯示項目符號？

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +可以發現到，第$1$連鎖沒有獎勵，**$2$連鎖～$5$連鎖的獎勵倍增，而$5$連鎖以上都固定是每次加$32$分**。
這行粗體的字比不粗的還多 🤔 這樣是不是起不到強調作用ㄌ

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +| $\ge$11 |  10  |
還是乾脆把表裡的數字用$$包一包xD

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +也就是說，如果$k$是1，而且只消除四顆氣泡，那以上三種獎勵函數的值都是$0$，此情況就直接定義得分為$10t=40$分；而其他情況就照著上面的表帶值，算完總和後一樣在外面乘以$10t$。
nit: ~~$k$是1~~ $k = 1$？

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
「中盤概念」可能用internal link? 不知道語法xD

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +以5A5B的情況為例，不考慮落下得分，則兩連鎖與一連鎖同消的得分如下：
是不是要解釋一下5A5B 🤔

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/index.md
> +layout: post
@crs38c28 忘了是不是該用`layout: null`，因為這頁沒有打算寫東西吧。

2019-01-11 02:18 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +| $k$的值 | 連鎖獎勵$R(k)$ |
函數名好像要用`\mathit`才標準，但沒關係xD

2019-01-13 16:52 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +也就是說，如果$k$是1，而且只消除四顆氣泡，那以上三種獎勵函數的值都是$0$，此情況就直接定義得分為$10t=40$分；而其他情況就照著上面的表帶值，算完總和後一樣在外面乘以$10t$。
好

2019-01-13 16:53 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +以5A5B的情況為例，不考慮落下得分，則兩連鎖與一連鎖同消的得分如下：
這個打算在前面點的條目講到，例如序盤之類。那邊寫了之後這邊再加個註解連過去吧？

2019-01-13 16:56 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +* 第$k$連鎖的連結數$l$
ｈｍｍ，因為如果寫了是每個連結的氣泡數就不能只用l了，但是如果在這邊加了下標怕閱讀上會不便
這邊的呈現方式是先讓他們知道跟連結數有關，後面才詳細說。不知道有沒有更好的呈現方式？

2019-01-13 16:56 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +也就是（$\sum_{k=1}^{n}$第$k$連鎖得分＋連鎖發動前累積的落下得分）除以$70$的商；這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
喔好ㄛ

2019-01-13 16:57 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +| 19 |  512  |
原本想說不要寫太general怕讀者閱讀困難...看來這邊還是寫得general點解釋清楚好了

2019-01-13 17:01 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +10t\left( R(k)+C(c)+\sum_{i=1}^{g} L(l_i) \right), \ 若(k,t)\neq(1,4)
剛剛用https://www.mathjax.org/#demo測了下發現可以用cases

2019-01-13 17:02 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +title: 障礙氣泡量公式
甚麼意思，是指關聯條目嗎 XD

2019-01-13 17:03 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +可以發現到，第$1$連鎖沒有獎勵，**$2$連鎖～$5$連鎖的獎勵倍增，而$5$連鎖以上都固定是每次加$32$分**。
還好，覺得這表示他們都很重要 XD

2019-01-13 17:03 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +| $\ge$11 |  10  |
好

2019-01-13 17:04 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +| $k$的值 | 連鎖獎勵$R(k)$ |
原來，我平常寫都沒用mathit說

2019-01-13 17:12 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +| 19 |  512  |
我想這邊我就還是保持原樣，然後文章最後多加一段討論2顆消等等的情況吧
因為例如2顆消的情況，連結獎勵也不一樣，這樣要討論的就多了；前面我希望能盡早清楚解釋公式

2019-01-13 17:33 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +\text{送給對手的障礙氣泡總數} = \left\lfloor\frac{\sum\text{第$k$連鎖得分}S_k + \text{連鎖發動前累積的落下得分}}{70}\right\rfloor
好，我把1/70放在外面比較好看
下面的summation是指哪裡呢？

2019-01-13 17:34 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +也就是（$\sum_{k=1}^{n}$第$k$連鎖得分＋連鎖發動前累積的落下得分）除以$70$的商；這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
怕讀者看不懂下高斯所以用商的概念再解釋一次 XD 不然我解釋下意思是向下取整，而不再寫一次原公式好了

2019-01-13 17:37 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
不會 BibleThump

2019-01-14 02:43 UTC, michaeimm commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
https://jekyllrb.com/docs/liquid/tags/#linking-to-posts
是這東西嗎？

2019-01-27 11:20 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
可能是yo

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/C_tactics/ii_main_chain_and_side_chain/1_key_puyo.md
> +1. 從C行綠色引爆有四連鎖。
nit: 直接寫`2.`？

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +title: 障礙氣泡量公式
就類似幫頁面分類吧，方便以標籤查找相關的頁面

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +其中$\lfloor \ \rfloor$是向下取整，整個公式的意思是取括號內數字除以$70$的商。這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
也可以把`\lfloor` `\rfloor`分成兩個inline math

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +* 第$k$連鎖的連結數$l$
寫`\sum_i l_i`？至少這樣可以先帶出`l`可以不止一個XD

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +### 1. 氣泡數$t$
或者說到底是不是不要用項目符號 xD

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +$k$的值與連鎖獎勵（命名為$R(k)）$的關係由下表給出：
右邊的`$`錯位置了？

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +| $\ge$11 |  $10$  |
`11`不用放在math mode麼？

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +現在，我們可以用上面這些數字來表示第$k$連鎖得分的公式了。令第$k$連鎖消除的總氣泡數為$t$，消除了$c$個顏色。另外，假設第$k$連鎖消除的所有氣泡分成$g$個連結群，而每一群有$l_i$個氣泡，$i=1,⋯,g$（因此$\sum_{i=1}^{g}l_i=t$）。
nit: `⋯` -> `\cdots`?

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +10t\left( R(k)+C(c)+\sum_{i=1}^{g} L(l_i) \right), \ \text{若}(k,t)\neq(1,4)
要將`\ `改成`&`麼？這樣可以對齊耶

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +公式中的落下得分，其計算方式為，緩降（soft drop）時氣泡經過一格加一分。發動完$n$連鎖後，累積的這些落下得分與每次連鎖得分相加，除完$70$的商是障礙氣泡量，餘數則保存起來，待下次發動連鎖時一倂納入計算。$n$連鎖中每個連鎖的分數都是個別計算，彼此不相關，算完後加總起來。以下讓$k$固定，討論第$k$連鎖的得分S_k$的計算方式。
`S_k`沒有了前面的`$`

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/C_tactics/ii_main_chain_and_side_chain/4_cross.md
> +[^2]: [ゆっくり解説　ぷよ用語解説戦術編　その１３，2:20～](ゆっくり解説　ぷよ用語解説戦術編　その１３).
這個連結不是連結XD 沒有url

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +## 第$k$連鎖得分$S_k$
heading後面空一行

2019-02-08 08:56 UTC, kar8uncle commented on _wiki/C_tactics/ii_main_chain_and_side_chain/1_key_puyo.md
> +換個角度想，**如果不放上那顆紅色，那二樓與一樓就接不起來，可以將二樓作為副砲。**F行的這顆紅色可以把連鎖接起來，我們就把他稱為*關鍵氣泡*，而在這裡，我們刻意不放上關鍵氣泡，藉此將連鎖拆成數段，利於中盤的攻防。如此作出來的副砲，可當作小連鎖騷擾對方／防禦對方；如果副砲無利可圖時，再把關鍵氣泡放上，與主砲連起來即可。
後面寫的時候最後的標點都不在粗體裡呢，這個也要統一麼？

2019-02-08 10:10 UTC, aclivtak commented on _wiki/C_tactics/ii_main_chain_and_side_chain/1_key_puyo.md
> +換個角度想，**如果不放上那顆紅色，那二樓與一樓就接不起來，可以將二樓作為副砲。**F行的這顆紅色可以把連鎖接起來，我們就把他稱為*關鍵氣泡*，而在這裡，我們刻意不放上關鍵氣泡，藉此將連鎖拆成數段，利於中盤的攻防。如此作出來的副砲，可當作小連鎖騷擾對方／防禦對方；如果副砲無利可圖時，再把關鍵氣泡放上，與主砲連起來即可。
是我寫錯了 XD 我是打算標點都不含在粗體裡的

2019-02-08 10:21 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +10t\left( R(k)+C(c)+\sum_{i=1}^{g} L(l_i) \right), \ \text{若}(k,t)\neq(1,4)
哇感謝，學到一課

2019-02-08 10:24 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +* 第$k$連鎖的連結數$l$
我用 第$k$連鎖的各連結數$l_i$ 這樣的呈現方式好了~
$\sum_i l_i$好像只有一個數，而且各連結群是分開計算，不該sum起來XD

2019-02-08 10:27 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +其中$\lfloor \ \rfloor$是向下取整，整個公式的意思是取括號內數字除以$70$的商。這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
分成兩個inline math？為甚麼要這樣做呀 🤔

2019-02-08 10:37 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
[中盤概論]({{ site.baseurl }}{% post_url _wiki/C_tactics/b_middle/i_intro.md %})
是這樣麼 XD

2019-02-08 10:38 UTC, aclivtak commented on _wiki/D_rules/a_scoreformula.md
> +title: 障礙氣泡量公式
🤔  不太知道語法怎麼寫，我先用文內comment的方式作吧

2019-02-08 11:27 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +講完了公式，我們終於可以依此算出每個連鎖的得分了！來回憶一下在中盤概論提到的概念，
之後再斟著XD

2019-02-08 11:27 UTC, kar8uncle commented on _wiki/D_rules/a_scoreformula.md
> +其中$\lfloor \ \rfloor$是向下取整，整個公式的意思是取括號內數字除以$70$的商。這個$70$就是「障礙氣泡的換算率」，預設為$70$，在近幾個版本玩家都能在遊戲內調整換算率。
覺得用`\ `好像有點奇怪XD

2019-02-08 11:28 UTC, kar8uncle commented
`layout: post`是不是錯了？應該是`wiki`? 現在網站生成失敗了

2019-02-08 16:17 UTC, aclivtak commented
中盤概論的index.md是layout: post呢... 🤔

2019-02-14 12:41 UTC, kar8uncle approved these changes

2019-02-14 12:44 UTC, merged