modify _plugins & add twitch,niconico,youtube plugins.
puyotw/core-site pull request #3
Opened 2018-12-29 14:58 UTC by Hilomair

fix dir name _scripts to _plugins

add youtube.rb , niconico.rb twitch.rb in _plugins

can embed those websites' vedios

2018-12-29 15:26 UTC, kar8uncle requested changes
vim的`.swp`也進來了 Kappa

把他拿出repo喔，還有如果怕錯手加了就把`.swp`放到.gitignore吧。

另外如果能統一使用單引號我會很欣慰 (X

2018-12-29 15:26 UTC, kar8uncle commented on _config.yml
> +plugins_dir: ./_plugins
這個整行拿掉之後，能用麼？因為這是Jekyll預設的，不用寫都能用的話就最好了。

2018-12-29 15:26 UTC, kar8uncle commented on _pages/about.md
> +{% twitch clip ArtisticRelievedChoughDxCat %}
這些測試用的應該不用丟進去XD

2018-12-29 15:26 UTC, kar8uncle commented on _plugins/niconico.rb
> +=end
這些不用的代碼可以刪掉了。

2018-12-29 15:26 UTC, kar8uncle commented on _plugins/niconico.rb
> +      raise "No Niconico ID provided in the \"niconico\" tag"
nit: 單引號？

2018-12-29 15:26 UTC, kar8uncle commented on _plugins/niconico.rb
> +      "<div class=\"video-container mb3\"><iframe width=\"560\" height=\"400\" frameborder=\"0\" allowfullscreen src=\"https://embed.nicovideo.jp/watch/#{@id}?;showinfo=0\"></iframe></div>"
如果單引號也可以用`#{@id}`，那這個也改成單引號吧。看到escape整個不舒服XD

@crs38c28 `iframe`的`width`和`height`要寫麼？

2018-12-29 15:26 UTC, kar8uncle commented on _plugins/niconico.rb
> +  Syntax = /^\s*([^\s]+)?/
`?`是指前面的`[^\s]+`（一個或多個非空白的字元）可有可無，但其實我們是必須有的。

我想應該是`/^\s*([^\s]+)/`？

2018-12-29 15:26 UTC, kar8uncle commented on _plugins/youtube.rb
> +  Syntax = /^\s*([^\s]+)?/
應該跟`Niconico`一樣改法。

2018-12-29 15:32 UTC, Hilomair commented on _config.yml
> +plugins_dir: ./_plugins
能用 我都是在這狀態下測試後面的東西的

2018-12-30 01:22 UTC, kar8uncle requested changes
差不多ok了。謝謝！

還有要把_config.yml的plugins_dir拿掉。

2018-12-30 01:22 UTC, kar8uncle commented on .gitignore
> +.swp
這個應該不行呢，要有wildcard在前面。

我看直接就拿別人的[vim .gitignore](https://github.com/github/gitignore/blob/master/Global/Vim.gitignore)好了：
```
# Swap
[._]*.s[a-v][a-z]
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
```

2018-12-30 01:22 UTC, kar8uncle commented on _plugins/niconico.rb
> +      "<div class='video-container mb3'><iframe width='560' height='400' frameborder='0' allowfullscreen src='https://embed.nicovideo.jp/watch/#{@id}?;showinfo=0'></iframe></div>"
喔不是，是指最外層的引號用單引號。html標準是雙引號的。其他也是最外層用單就好了。

2018-12-30 01:23 UTC, kar8uncle commented on _config.yml
> +plugins_dir: ./_plugins
話說要把這行拿掉喔

2018-12-30 01:38 UTC, kar8uncle commented on _plugins/niconico.rb
> +      raise "No Niconico ID provided in the \"niconico\" tag"
看來ruby社群是習慣都用雙引號的。所以關於引號的留言都可直接無視。抱歉

2018-12-30 01:55 UTC, merged

2018-12-30 01:56 UTC, kar8uncle commented
至於`iframe`的`width`跟`height`感覺是不需要的。待我們弄theme的時候再斟酌這個吧。